# Generated by Django 3.2.3 on 2021-05-30 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='imageorvideo',
            field=models.FileField(default='logo.png', help_text='You can only upload a image or a video.', upload_to='portfolio/', verbose_name='Image or Video'),
        ),
    ]
